### ISSUE TITLE
possible failure to detect a deletion

### ISSUE THREAD

**Issue by dmnfarrell** [uio-cels/NucDiff#11]
Is there any reason you can suggest that nucdiff would fail to detect a large deletion in the case shown below. The reads on top were aligned to a reference and show a large gap as expected. The contigs from an assembly using those reads are also shown below that with the same gap. When nucdiff is run with the assembly on the same reference it (the highlighted track) doesn't show the deletion. The other tracks are not relevant.

![rd12](https://user-images.githubusercontent.com/7859189/68402323-0aa9fa00-0173-11ea-9651-bb96f5ea70fc.png)

thanks.

**Comment by kseniakh** [comment]
Hello, 

In general, NucDiff may report a relocation instead of a deletion when the length of the deleted region is more than 10Kb bases. You can change the --reloc_dist parameter value to check if you get the expected results. Unfortunately, I can't say you more based on the figure provided since I'm a little confused what tracks are relevant and what are not.

Ksenia

**Comment by dmnfarrell** [comment]
Thanks for your reply. Changing --reloc_dist to 20000 doesn't change the result in this case. This deletion is 13000 bases. The top 3 tracks are only relevant. Would you consider this a bug since it appears to be a simple deletion and not a relocation. If not are there any other parameters you would suggest in nucmer or delta-filter that might allow these large deletions to marked as such.

**Comment by kseniakh** [comment]
Can you then provide me all entries for the given contig in:
- prefix.coords file produced by nucmer
- prefix_query_blocks.gff
- prefix_query_struct.gff 
to find out what is going on there ?

**Comment by dmnfarrell** [comment]
I've attached all the results files zipped:
[MTB-H37Rv_Morygis_IK1351.zip](https://github.com/uio-cels/NucDiff/files/3821585/MTB-H37Rv_Morygis_IK1351.zip)
The prefix used is query which is a bit confusing I know. The track in my screenshot is from the _ref_struct.gff though. They are bacterial genomes, one is an assembly. I can give you the sequences if you need them.

cheers.

**Comment by kseniakh** [comment]
According to the nucmer results, none of the contigs spans this region so there is no way for the deletion to be detected. There is only NODE_13 at the left side of the gap and NODE_40 at the right side of the gap. You can see their borders at the second track in the figure. You can click on them to get detailed information about mapped blocks.

**Comment by dmnfarrell** [comment]
Ok that makes sense. There are more gaps in the assembly than I realised. Thanks for your help.
