### ISSUE TITLE
Mummer4

### ISSUE THREAD

**Issue by JonEilers** [uio-cels/NucDiff#12]
Are there plans to update NucDiff to support mummer4 use? I am working with some larger genomes that are too large for mummer3.

**Comment by kseniakh** [comment]
I have heard about the Mummer4, but still don't have time to test it. However, if it produces the .delta file similar to the Mummer3, you can try to parse it with NucDiff.

**Comment by dbtara** [comment]
mummer4 output is in the same format as mummer3. Only the nucmer was made multithreaded so it basically plugs in well.

**Comment by MaestSi** [comment]
Hi, are there any news on the integration of MUMmer4 in NucDiff pipeline?
Thanks,
Simone

**Comment by kseniakh** [comment]
Hi Simone, 

According to the [manual ](https://mummer4.github.io/manual/manual.html), commands and output files remain the same in the MUMmer4. So there shouldn't be any difference for NucDiff what version of MUMmer is installed.
