### ISSUE TITLE
ERROR: The provided file with an assembly does not exist

### ISSUE THREAD

**Issue by mamora** [uio-cels/NucDiff#14]
I am trying to run nucdiff with a delta file but I keep getting an error:

nucdiff np.pilon.fasta  pilon_pitgg_pacBio.fasta results np_gg  --delta_file np_gg.delta --ref_name_full yes

ERROR: The provided file with an assembly does not exist

If I run nucdiff without the delta file I get the same error

I already checked that the delta file is installed in the right directory and that mummer is installed in my $PATH so I have no more ideas? 

Does nucdiff requires the mum file also?

**Comment by kseniakh** [comment]
The tool cannot find the file with the assembly (or the query genome). Check the path to  pilon_pitgg_pacBio.fasta

**Comment by mamora** [comment]
thanks
