### ISSUE TITLE
Ambiguous ("N") handling and Results interpretation

### ISSUE THREAD

**Issue by chrisgulvik** [uio-cels/NucDiff#25]
## Handling Ns
It looks like with default parameters in `nucdiff` that N comparisons are treated unexpectedly. In other words, N -vs- {A,T,C,G} is reported as a mismatch. Any recommendations handling "N"-containing genomes? The latest `nucdiff` in bioconda has nucmer 3.1 but v4 reports a possible fix involving adding the "-B" argument to the show-coords system call. It looks like nucdiff default [lacks this -B arg](https://github.com/uio-cels/NucDiff/blob/master/nucdiff/class_nucmer.py#L93) perhaps because it would disrupt downstream outfile parsing.

## Results Interpretation
Different values are reported for "Substitution" and "substitution" shown below. Is one ref and one query? Or how do I interpret Test 2 and Test 3 results below?

I made and ran a test suite to show that here:
Initial tests making my own fake short contig didn't even align. So, I used a bacterial genome ~2.3 Mbp size. 3 general "tests" show this (first of which is a control).

`cd NucDiff_Test_Ambiguities ` [NucDiff_Test_Ambiguities.tar.gz](https://github.com/uio-cels/NucDiff/files/6113091/NucDiff_Test_Ambiguities.tar.gz)

## View SNP tally of self-aligned assembly with 0 Ns
`nucdiff H4011.0Ns.fna H4011.0Ns.fna Self_H4011_Comparison_0Ns pref `
`grep ubstitution Self_H4011_Comparison_0Ns/results/*.out `
&nbsp;&nbsp;&nbsp;&nbsp;    #    Substitutions   0
&nbsp;&nbsp;&nbsp;&nbsp;    #    substitution    0
`grep 'Unaligned sequences' Self_H4011_Comparison_0Ns/results/*.out `
&nbsp;&nbsp;&nbsp;&nbsp;    #    Unaligned sequences     0
&nbsp;&nbsp;&nbsp;&nbsp;    # RESULTS: positive control here shows 0 SNPs with complete self-alignment

## Test 1: how 9-bp consecutive stretch of Ns self-aligned is reported; Ns were added to largest contig
`nucdiff H4011.9-bp-consecutive-Ns.fna H4011.9-bp-consecutive-Ns.fna Self_H4011_Comparison_9-bp-consecutive-Ns pref `
`grep -e 'ubstitution' -e $'^gap\t' Self_H4011_Comparison_9-bp-consecutive-Ns/results/*.out `
 &nbsp;&nbsp;&nbsp;&nbsp;   #     Substitutions   1
 &nbsp;&nbsp;&nbsp;&nbsp;   #     substitution    0
 &nbsp;&nbsp;&nbsp;&nbsp;   #     gap     1
`grep 'Unaligned sequences' Self_H4011_Comparison_9-bp-consecutive-Ns/results/*.out `
 &nbsp;&nbsp;&nbsp;&nbsp;   #     Unaligned sequences     0
 &nbsp;&nbsp;&nbsp;&nbsp;   # RESULTS: 1 SNP and 1 gap reported, complete self-alignment occurred again
 &nbsp;&nbsp;&nbsp;&nbsp;   # INTERPRET: ???

## Test 2: how 9 Ns scattered in largest contig (at least 50 bp away from each other, no consecutive Ns) are reported when self-aligned
`nucdiff H4011.9-bp-scattered-Ns.fna H4011.9-bp-scattered-Ns.fna Self_H4011_Comparison_9-bp-scattered-Ns pref `

`grep -e 'ubstitution' -e $'^gap\t' Self_H4011_Comparison_9-bp-scattered-Ns/results/*.out `
&nbsp;&nbsp;&nbsp;&nbsp;    #     Substitutions   9
&nbsp;&nbsp;&nbsp;&nbsp;    #     substitution    0
&nbsp;&nbsp;&nbsp;&nbsp;    #     gap     9
`grep 'Unaligned sequences' Self_H4011_Comparison_9-bp-consecutive-Ns/results/*.out `
 &nbsp;&nbsp;&nbsp;&nbsp;    #    Unaligned sequences     0
 &nbsp;&nbsp;&nbsp;&nbsp;    # RESULTS: 9 SNPs, 9 gaps reported, full-self alignment reported too
  &nbsp;&nbsp;&nbsp;&nbsp;   # INTERPRET: 9 SNPs, 0 gaps ref-against-query, and 0 SNPs, 9 gaps query-against-ref ???

**Comment by kseniakh** [comment]
If you are not interested in the 'N'- related differences, just filter out the differences containing 'gap' in their names. 

There is no error in the provided output files. Substitution=substitution + gap. 
The full description and the example of the <prefix>_stat.out file can be found here: https://github.com/uio-cels/NucDiff/wiki/stat.out

**Comment by chrisgulvik** [comment]
Thanks for the recommendation to just ignore the 'gap' counts when evaluating "N"-containing assemblies.

Adding gap counts to SNPs to report "Substitution"s was unexpected, and the wiki doesn't clarify that. The https://github.com/uio-cels/NucDiff#42-types-of-differences figure is super helpful though at showing how the uppercase labels are calculated. Thanks for making that fig!
