### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by hassantarabai** [uio-cels/NucDiff#29]
Hello,

I am using nucdiff to compare between two closely related genomes. Its working with the masked genomes but when using the original unmasked genomes, i am ending up with the following error:
ERROR: 'contig1010' not found in reference file

Any advice how to resolve it ?

Thank you,

**Comment by hassantarabai** [comment]
Hello,

I am using nucdiff to compare between two closely related genomes. Its working with the masked genomes but when using the original unmasked genomes, i am ending up with the following error: 
ERROR: 'contig1010' not found in reference file

Any advice how to resolve it ? 

Thank you,

**Comment by kseniakh** [comment]
Hello,

This is something wrong with nucmer and not nucdiff. Try to look here: https://github.com/mummer4/mummer/issues/125 . May be it can be useful for you as well.
