### ISSUE TITLE
same FastA content prints "Differences ... are found"

### ISSUE THREAD

**Issue by chrisgulvik** [uio-cels/NucDiff#4]
Both of these statements are printed, suggesting there were differences found between the two files provided, but since I gave it the same file as Ref and Query, these statements are incorrect:

`Differences inside fragments are found`
`Differences between fragments are found`

The *Output_dir/Prefix_stat.out* file lists 0 in the second column for all differences except for the tail which lists the # sequences for each.

If two different file names are provided, but happen to be identical sequences, it might be useful to instead report `No differences were found`. Perhaps in the FIND_STATISTICS function you could add a total count variable and report when total == 0 or even just print what total equals, maybe `'Total differences observed: {}'.format(total)`?

**Comment by kseniakh** [comment]
In order to avoid confusions in cases when no differences were found, I have changed these runtime printouts to :

 `The difference detection inside fragments step is complete`
 `The difference detection between fragments step is complete`
