### ISSUE TITLE
uncovered ref regions

### ISSUE THREAD

**Issue by jaworskicoline** [uio-cels/NucDiff#5]
Hello,
in the summary stats files appear those two lines:
"Uncovered ref regions num"
"Uncovered ref regions len"
I was unable to find the exact definition in the manuscript nor in the github definition list. Would you mind explaining how they were calculated ?
egf, how is a region defined (how many bases in a row) ?, Is the uncovered ref regions length the sum of the lengths of all uncovered regions ? etc.
Thank you so much !
Coline

**Comment by kseniakh** [comment]
Hello,

The definitions are given in the wiki manual page : https://github.com/uio-cels/NucDiff/wiki/stat.out

Uncovered ref regions num - the number of reference regions that were not covered by any query sequence (or mapped block)
Uncovered ref regions len -  the number of bases inside these regions

**Comment by jaworskicoline** [comment]
Thank you !!
But you had some working definition for defining an uncovered region ? eg a minimum length ? to be considered as something different than deletion in the template assembly ?

Or, just by identifying the names of sequences in the reference genome that were not called in the alignment ?

Thank you
Coline

**Comment by kseniakh** [comment]
Uncovered regions consist of bases that were not met in the NUCmer output file and are not a part of any detected difference. Information about exact coordinates of uncovered regions is given in ref_additional.gff as "uncovered_region" entries.

**Comment by jaworskicoline** [comment]
OK, thank you very much for the clarification.
Coline
