### ISSUE TITLE
Not able to run NucDiff on an existing .delta file generated by nucmer

### ISSUE THREAD

**Issue by pulichandramoulireddy** [uio-cels/NucDiff#6]
Hi,
I have tried to run NucDiff on an existing .delta file and it gave me the following error.

python  NucDiff-master/nucdiff.py --proc 8  --delta_file  ../hma_hvul1.delta --ref_name_full yes --query_name_full yes ../hma.fasta ../hvul_mod.fasta ./nucdiff_out test

Run NUCmer...

Traceback (most recent call last):
  File "NucDiff-master/nucdiff.py", line 101, in <module>
    main()
  File "NucDiff-master/nucdiff.py", line 99, in main
    START(args)
  File "NucDiff-master/nucdiff.py", line 56, in START
    struct_dict,end_err_dict,unmapped_list,uncovered_dict=find_errors.FIND_ERRORS_ASSEMBLY(file_ref,file_contigs, working_dir, nucmer_opt, prefix,proc_num, filter_opt,delta_file,reloc_dist,coord_file ) #class Errors
  File "/home/hydra/mouli/projects/Hydra_Genome/compare_hmag_hvul/nucdiff/NucDiff-master/find_errors.py", line 24, in FIND_ERRORS_ASSEMBLY
    nuc.RUN(nucmer_opt,filter_opt)
  File "/home/hydra/mouli/projects/Hydra_Genome/compare_hmag_hvul/nucdiff/NucDiff-master/class_nucmer.py", line 83, in RUN
    subprocess.check_call(call_line, shell=True)
UnboundLocalError: local variable 'call_line' referenced before assignment

**Comment by kseniakh** [comment]
Hi,
I have fixed a bug. Can you check if everything is working now?

**Comment by pulichandramoulireddy** [comment]
Hi,
Thanks for the response. I tried running the above command and did not worked but found a work around. But found couple of more issues. 

work around (tried): I have to copy the file (nucmer outfile) to the ./nucdiff_out and give the prefix of the file (i guess it matches the prefix).
eg: " python NucDiff-master/nucdiff.py --proc 8  --delta_file ../hma_hvul1.delta --ref_name_full yes --query_name_full yes ../hma.fasta ../hvul_mod.fasta ./nucdiff_out hma_hvul1"

It created the following files successfully :
hma_hvul1_1.coord
hma_hvul1_2.coord
hma_hvul1.coords
hma_hvul1.filter
results
hma_hvul1_1.snps
hma_hvul1_2.snps
hma_hvul1.delta
hma_hvul1_filtered.snps

Isuues:
1. hma_hvul1_filtered.snps is not populated
2. In results folder it could not output all the files only following files were written
    hma_hvul1_query_snps.gff
    hma_hvul1_query_struct.gff
    hma_hvul1_ref_blocks.gff
    hma_hvul1_ref_snps.gff (this file is not populated)
3. Though I have given "--proc 8" it used only one thread and took more than 24hrs and run has stopped with the following error. 
" hydra@hydra[nucdiff] python NucDiff-master/nucdiff.py --proc 8  --delta_file ../hma_hvul1.delta --ref_name_full yes --query_name_full yes ../hma.fasta ../hvul_mod.fasta ./nucdiff_out hma_hvul1 

Run NUCmer...


Find differences...

The difference detection inside fragments step is complete

The difference detection between fragments step is complete
Traceback (most recent call last):
  File "NucDiff-master/nucdiff.py", line 101, in <module>
    main()
  File "NucDiff-master/nucdiff.py", line 99, in main
    START(args)
  File "NucDiff-master/nucdiff.py", line 67, in START
    generate_output.GENERATE_OUTPUT(struct_dict,end_err_dict,unmapped_list, file_ref, file_contigs, working_dir, prefix,err_ref_cont_coord_errors_list,statistics_output_lines,asmb_name_full,ref_name_full,cont_blocks_dict,vcf_flag)
  File "/home/hydra/mouli/projects/Hydra_Genome/compare_hmag_hvul/nucdiff/NucDiff-master/generate_output.py", line 1695, in GENERATE_OUTPUT
    OUTPUT_REF_ASSEM_TABLE(err_ref_cont_coord_errors_list, ref_dict,ref_names,ref_full_names_dict,contigs_dict,contig_names,contig_full_names_dict,working_dir, 'results/'+prefix,asmb_name_full,ref_name_full,mapped_blocks_dict,vcf_flag)
  File "/home/hydra/mouli/projects/Hydra_Genome/compare_hmag_hvul/nucdiff/NucDiff-master/generate_output.py", line 954, in OUTPUT_REF_ASSEM_TABLE
    c_name=ref_full_names_dict[entry[3]]
KeyError: 'Hvul_158915'   "

I guess this error could be due to unpopulated file " hma_hvul1_ref_snps.gff ".

Your help in sorting out these issues will be of great use. Thanks.

Mouli.

**Comment by kseniakh** [comment]
Hi Mouli,

Excuse me for the delay. Now the bug is fixed. You can try it again. 

Related to the long execution time: For now, parallelization is performed only for SNP detection, NUCmer and other NucDiff steps require only 1 thread. Unfortunately, it may take 1-2 days in some cases. 

Related to unpopulated hma_hvul1_filtered.snps: it is normal to be empty for this file. 

Ksenia

**Comment by pulichandramoulireddy** [comment]
Hi Kseniakh,
Things are working smoothly now. Isssues I have mentioned in this thread are solved. Thank you very much for the time and efforts. I would like to congratulate for the development of this wonderful tool. It is very simple and especially GFF3 out put makes life very easy.  Thanks a lot.

**Comment by ghuryejay** [comment]
Hi,

I am running this command:

`python nucdiff.py --proc 8  --ref_name_full yes --query_name_full yes --delta_file out.delta PRJNA253696.fasta  scaffolds.fasta out pre`

Although I provide the delta file, I get this result:
```
Run NUCmer...

ERROR: Could not parse delta file, out/pre.delta
error no: 400

Could not run delta-filter. Please, check delta-filter input parameters values.
```

Can you tell me whats going wrong here?

Thanks.

**Comment by kseniakh** [comment]
Hello,

The problem is that delta-filter was not able to open the out.delta file. You can try to input  ./out.delta instead of out.delta or provide the full path to the file. I think it will help. 


Ksenia

**Comment by kseniakh** [comment]
Hello,

Probably, there is a problem with the delta file itself. If there is a path problem, then the commands from the previous messages won't run as well. But as I know, you have successfully run them. The easiest way to solve it is to run the full analysis from the beginning and let the tool to generate a new delta-file. 


Ksenia

**Comment by haqle314** [comment]
Hi,
I believe the issue here is in `class_nucmer.py`. Inside `RUN`, `delta-filter` is called with `prefix + ".delta"` instead of the value of `delta_file` like it should.

**Comment by MaestSi** [comment]
Hi, I am facing an issue similar to @ghuryejay 's using NucDiff v2.0.3. I tried to provide as `Prefix` argument the same name of my pre-generated .delta file (without the file extension) as proposed by @haqle314 , but still I am having the same error. Any advice?
Thanks,
Simone

**Comment by kseniakh** [comment]
Hi MaestSi,  

Can you provide your command and error message?

**Comment by MaestSi** [comment]
Sure!
I first generated and filtered the delta file using MUMmer4 with:


```
QUERY=$1
REFERENCE=$2
MIN_AL_LEN=1000
THREADS=32

SAMPLE_NAME=$(echo $(basename $REFERENCE) | sed 's/\.fasta//')"_VS_"$(echo $(basename $QUERY) | sed 's/\.fasta//')

nucmer -t $THREADS --maxmatch --noextend -p $SAMPLE_NAME $REFERENCE $QUERY
delta-filter -1 -l $MIN_AL_LEN $SAMPLE_NAME".delta" > $SAMPLE_NAME"_minal"$MIN_AL_LEN"_filtered.delta"

```
And then I ran NucDiff with:

```
nucdiff --proc $THREADS --ref_name_full yes --query_name_full yes --vcf yes \
--delta_file $SAMPLE_NAME"_minal"$MIN_AL_LEN"_filtered.delta" \
$REFERENCE $QUERY "NucDiff_output_"$SAMPLE_NAME"_MUMmer4" $SAMPLE_NAME"_minal"$MIN_AL_LEN"_filtered"
```

The error is get is:

```
ERROR: Could not parse delta file, /path/to/$SAMPLE_NAME"_minal"$MIN_AL_LEN"_filtered.delta"
error no: 400

Run NUCmer...


Could not run delta-filter. Please, check delta-filter input parameters values.

```

Thanks,
Simone

**Comment by MaestSi** [comment]
Hi,
I was using NucDiff version 2.0.3 installed from conda. I also tried to clone this repository and to create an environment based on python 2.7, where I installed Biopython package v1.77 and MUMmer4. I then ran the same command as before, but specifying `python /home/simone/software/NucDiff/nucdiff/nucdiff.py` instead of `nucdiff`.
This time I got this error:

```
Traceback (most recent call last):
  File "/home/simone/software/NucDiff/nucdiff/nucdiff.py", line 17, in <module>
    from .find_errors import FIND_ERRORS_ASSEMBLY
ImportError: attempted relative import with no known parent package

```
Should I have installed any other python packages?
Thanks,
Simone

**Comment by kseniakh** [comment]
Hi Simone,

Can you just run  `nucmer -t $THREADS --maxmatch --noextend -p $SAMPLE_NAME $REFERENCE $QUERY`  without `delta-filter` command and use the output file ($SAMPLE_NAME".delta") as the input delta-file for NucDiff?  
If you need to have `-l $MIN_AL_LEN` , use `--filter_opt '-l $MIN_AL_LEN' ` as input argument when you are running nucdiff.

And be sure that the delta-file is renamed as was proposed above. I haven't noticed that there was a report about this bug  and will fix it yearly next year.

Were you running MUMmer4 through conda also?

If you want to run scripts from git without conda , you need to use: 
`python -m <dir_containing_scripts>.nucdiff` instead of nucdiff
(you should be in the directory containing<dir_containing_scripts> when you run the command)

**Comment by MaestSi** [comment]
Hi,
I just ran:

```
$NUCDIFF --proc $THREADS --ref_name_full yes --query_name_full yes --vcf yes \
--delta_file $SAMPLE_NAME".delta" \
--filter_opt '-l $MIN_AL_LEN' \
$REFERENCE $QUERY "NucDiff_output_"$SAMPLE_NAME"_MUMmer4" $SAMPLE_NAME
```

and got error:

```
ERROR: Could not parse delta file, $SAMPLE_NAME".delta"
error no: 400


Run NUCmer...


Could not run delta-filter. Please, check delta-filter input parameters values.

```
Simone

P.s.: this was obtained using the conda installation of NucDiff. I tried `with python -m /home/simone/software/NucDiff/nucdiff/nucdiff.py` and got error:
`/home/simone/miniconda3/envs/Nucdiff_env/bin/python: Relative module names not supported`

**Comment by kseniakh** [comment]
Hi,

In conda environment, run the same command but with the absolute paths:

```
$NUCDIFF --proc $THREADS --ref_name_full yes --query_name_full yes --vcf yes \
--delta_file <abs_path>/"NucDiff_output_"$SAMPLE_NAME"_MUMmer4"/$SAMPLE_NAME".delta" \
--filter_opt '-l $MIN_AL_LEN' \
$REFERENCE $QUERY <abs_path>/"NucDiff_output_"$SAMPLE_NAME"_MUMmer4" $SAMPLE_NAME

```
I assume that the problem is that nucdiff cannot find the file in the output dir. Providing the full paths in the input arguments should solve the problem. Be sure that the delta file in the <abs_path>/"NucDiff_output_"$SAMPLE_NAME"_MUMmer4" directory and is named as $SAMPLE_NAME".delta".

**Comment by MaestSi** [comment]
Hi @kseniakh ,
now it is running!
After running the following command with MUMmer4 (installed from conda):

```
#!/bin/bash
QUERY=$1
REFERENCE=$2
MIN_AL_LEN=1000
THREADS=32

WORKING_DIR=$(dirname $REFERENCE)
SAMPLE_NAME=$(echo $(basename $REFERENCE) | sed 's/\.fasta//')"_VS_"$(echo $(basename $QUERY) | sed 's/\.fasta//')

nucmer -t $THREADS --maxmatch --noextend -p $SAMPLE_NAME $REFERENCE $QUERY

```

I activate NucDiff environment and used command:

```
mkdir $WORKING_DIR"/NucDiff_output_"$SAMPLE_NAME"_MUMmer4"
cp $WORKING_DIR"/"$SAMPLE_NAME".delta" $WORKING_DIR"/NucDiff_output_"$SAMPLE_NAME"_MUMmer4"

nucdiff --proc $THREADS --ref_name_full yes --query_name_full yes --vcf yes \
--delta_file $WORKING_DIR"/"$SAMPLE_NAME".delta" \
--filter_opt '-l $MIN_AL_LEN' \
$REFERENCE $QUERY $WORKING_DIR"/NucDiff_output_"$SAMPLE_NAME"_MUMmer4" $SAMPLE_NAME
```

I'll let you know if it ends running successfully.
Thanks,
Simone
