### ISSUE TITLE
why --maxmatch is hard code

### ISSUE THREAD

**Issue by slbai01** [uio-cels/NucDiff#9]
Hi, 

Thanks for your work. 

I don't understand why the `--maxmatch` parameter is hard code when doing nucmer. Does this significantly affect the variation  calling results? 

I need to make a comparison of two larger genomes, even if I use mummer4 for chromosome comparison, if I add `--maxmatch` parameter, it is still very slow, each pair of chromosomes may take half a month, and the filtering result file will take a long time, this is unacceptable to me, so I want to use the `--mum` parameter.

Thanks

Shenglong

**Comment by kseniakh** [comment]
Hi,

--maxmatch is hard coded since this is the best option for detection of repeat-related differences. 
However, you can always run mummer yourself with any input parameters you like and use mummer output as input for nucdiff. 

Ksenia
